# Automatically generated file. DO NOT MODIFY
#
# This file is generated by vendor/xiaomi/camera/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/camera

PRODUCT_PACKAGES += \
    MiuiCamera
